_GITS_HOLE="GIT_SOURCE/"
_SERVER_DIRECTION="162.243.7.240"
_SERVER_PATH="/var/www/html/"
USER_ADMINCSPATH="/home/${USER}/server_admin_scripts"
_MSG="git remote add $1  ssh://${USER}@${_SERVER_DIRECTION}/home/${USER}/${_GITS_HOLE}${1}.git && git push --set-upstream ${1} master"